test: unpin isort
isort < 5 does still use distutils which is no longer available for
python >= 3.12.
This fixes:

ModuleNotFoundError: No module named 'distutils'