fix: Fix SBOM generation with python 3.8 due to unsupported operand in type definitions
As documented in https://peps.python.org/pep-0604/ using `|` is not supported in python 3.8.

https://docs.python.org/3/library/typing.html#typing.Union recommends using Union instead. This
commit makes the change from using `|` to Union.

This fixes the following error.

```
Traceback (most recent call last):
  File "cpc_sbom/__init__.py", line 5, in <module>
    from generate import generate_sbom
  File "/home/philroche/Working/cpc-sbom/cpc_sbom/generate.py", line 94, in <module>
    def _calculate_file_sha256sum(file_path: str | bytes) -> str:
TypeError: unsupported operand type(s) for |: 'type' and 'type'
```