fix: unpin python-apt
The pinned version doesn't work on a plucky system due to compile
problems.
This fixes:

building 'apt_pkg' extension
      clang++ -pthread -fno-strict-overflow -Wsign-compare -Wunreachable-code -DNDEBUG -g -O3 -Wall -fPIC -fPIC -I/home/tom/.cache/uv/builds-v0/.tmpYFpcgS/include -I/home/tom/.local/share/uv/python/cpython-3.12.7-linux-x86_64-gnu/include/python3.12
      -c python/acquire-item.cc -o build/temp.linux-x86_64-cpython-312/python/acquire-item.o -std=c++11 -Wno-write-strings -DAPT_8_CLEANER_HEADERS -DAPT_9_CLEANER_HEADERS -DAPT_10_CLEANER_HEADERS -DPY_SSIZE_T_CLEAN
[snipped]
error: command '/usr/bin/clang++' failed with exit code 1